SystemInfo/Models/ErrorViewModel.cs
using System;

namespace SystemInfo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SystemInfo/Models/InformationModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SystemInfo.Models
{
    public class InformationModel
    {
        public string OperatingSystem { get; set; }
        public string InfoTitle { get; set; }
        public string FrameworkDescription { get; set; }
        public string OSArchitecture { get; set; }
        public string ProcessArchitecture { get; set; }
        public string Memory { get; set; }
        public string IPAddressString { get; set; }
        public string WeatherBy { get; set; }
        public string CurrentTemperature { get; set; }
        public string CurrentIcon { get; set; }
        public string DailySummary { get; set; }
        public string CurrentCity { get; set; }
        public string UnitOfMeasure { get; set; }

    }

}

SystemInfo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SystemInfo.Models;

namespace SystemInfo.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SystemInfo/Controllers/InformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DarkSky.Models;
using DarkSky.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Globalization;
using System.IO;
using System.Net.Http;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using static System.Math;

namespace SystemInfo.Controllers
{
    public class InformationController : Controller
    {
        public string PublicIP { get; set; } = "IP Lookup Failed";
        public double Long { get; set; }
        public double Latt { get; set; }
        public string City { get; set; }
        public string CurrentWeatherIcon { get; set; }
        public string WeatherAttribution { get; set; }
        public string CurrentTemp { get; set; } = "undetermined";
        public string DayWeatherSummary { get; set; }
        public string TempUnitOfMeasure { get; set; }
        public readonly IHostingEnvironment _hostEnv;

        public InformationController(IHostingEnvironment hostingEnvironment)
        {
            _hostEnv = hostingEnvironment;
        }

        public IActionResult GetInfo()
        {
            Models.InformationModel model = new Models.InformationModel()
            {
                OperatingSystem = RuntimeInformation.OSDescription,
                FrameworkDescription = RuntimeInformation.FrameworkDescription,
                OSArchitecture = RuntimeInformation.OSArchitecture.ToString(),
                ProcessArchitecture = RuntimeInformation.ProcessArchitecture.ToString()
            };

            string title = string.Empty;
            string OSArchitecture = string.Empty;

            if (model.OSArchitecture.ToUpper().Equals("X64"))
            {
                OSArchitecture = "64-bit";
            }
            else
            {
                OSArchitecture = "32 bits";
            }

            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                title = $"Windows {OSArchitecture}";
            }
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
            {
                title = $"OSX {OSArchitecture}";
            }
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
            {
                title = $"Linux { OSArchitecture }";
            }

            GetLocationInfo().Wait();
            model.IPAddressString = PublicIP;

            GetWeatherInfo().Wait();
            model.CurrentIcon = CurrentWeatherIcon;

            model.WeatherBy = WeatherAttribution;
            model.CurrentTemperature = CurrentTemp;
            model.DailySummary = DayWeatherSummary;
            model.CurrentCity = City;
            model.UnitOfMeasure = TempUnitOfMeasure;

            model.InfoTitle = title;

            return View(model);

        }

        private DarkSkyService.OptionalParameters GetunitOfMeasure()
        {
            bool blnMetric = RegionInfo.CurrentRegion.IsMetric;
            DarkSkyService.OptionalParameters optParms = new DarkSkyService.OptionalParameters();

            if (blnMetric)
            {
                optParms.MeasurementUnits = "si";
                TempUnitOfMeasure = "C";
            }
            else
            {
                optParms.MeasurementUnits = "us";
                TempUnitOfMeasure = "F";
            }

            return optParms;
        }


        private string GetCurrentWeatherIcon(Icon ic)
        {
            string iconFilename = string.Empty;

            switch (ic)
            {
                case Icon.ClearDay:
                    iconFilename = "Sun.svg";
                    break;
                case Icon.ClearNight:
                    iconFilename = "Moon.svg";
                    break;

                case Icon.Cloudy:
                    iconFilename = "Cloud.svg";
                    break;

                case Icon.Fog:
                    iconFilename = "Cloud-Fog.svg";
                    break;

                case Icon.PartlyCloudyDay:
                    iconFilename = "Cloud-Sun.svg";
                    break;
                case Icon.PartlyCloudyNight:
                    iconFilename = "Cloud-Moon.svg";
                    break;

                case Icon.Rain:
                    iconFilename = "Cloud-Rain.svg";
                    break;

                case Icon.Snow:
                    iconFilename = "Snowflake.svg";
                    break;

                case Icon.Wind:
                    iconFilename = "Wind.svg";
                    break;
                default:
                    iconFilename = "Thermometer.svg";
                    break;
            }

            return iconFilename;

        }

        private async Task GetWeatherInfo()
        {
            string apiKey = "https://api.darksky.net/forecast/444d2c868cd209e1e72ba926eb8e0744/37.8267,-122.4233";
            DarkSkyService weather = new DarkSkyService(apiKey);
            DarkSkyService.OptionalParameters optParams = GetunitOfMeasure();
            var foreCast = await weather.GetForecast(Latt, Long, optParams);
            string iconFileName =
                GetCurrentWeatherIcon(foreCast.Response.Currently.Icon);
            string svgFile = Path.Combine(_hostEnv.ContentRootPath, "climacons", iconFileName);
            CurrentWeatherIcon = System.IO.File.ReadAllText($"{svgFile}");
            WeatherAttribution = foreCast.AttributionLine;
            DayWeatherSummary = foreCast.Response.Daily.Summary;
            if (foreCast.Response.Currently.Temperature.HasValue)
                CurrentTemp = Round(foreCast.Response.Currently.Temperature.Value, 0).ToString();
        }

        private async Task GetLocationInfo()
        {
            string API = "https://ipapi.co/8.8.8.8/json/";
            var httpClient = new HttpClient();
            string json = await httpClient.GetStringAsync(API);
            LocationInfo info = JsonConvert.DeserializeObject<LocationInfo>(json);

            PublicIP = "8.8.8.8";
            Long = -122.0838;
            Latt = 37.386;
            City = "Mountain View";
            //PublicIP = info.ip;
            //Long = info.longitude;
            //Latt = info.latitude;
            //City = info.city;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

SystemInfo/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

SystemInfo/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SystemInfo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

SystemInfo/Views/Information/GetInfo.cshtml
@model IEnumerable<SystemInfo.Models.InformationModel>

@{
    ViewData["Title"] = "GetInfo";
}

<h2>GetInfo</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.OperatingSystem)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.InfoTitle)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FrameworkDescription)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OSArchitecture)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProcessArchitecture)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Memory)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IPAddressString)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.WeatherBy)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CurrentTemperature)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CurrentIcon)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DailySummary)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CurrentCity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UnitOfMeasure)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OperatingSystem)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InfoTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FrameworkDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OSArchitecture)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProcessArchitecture)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Memory)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IPAddressString)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WeatherBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CurrentTemperature)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CurrentIcon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DailySummary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CurrentCity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UnitOfMeasure)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

SystemInfo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SystemInfo</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SystemInfo</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Information" asp-action="GetInfo">Information DashBoard</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - SystemInfo</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>